---
- name: AWS role
  ansible.builtin.import_role:
    name: aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      private_domain: "private_domain"
      root_password: "mysql_root_password"

- name: Mysql Role
  ansible.builtin.import_role:
    name: inqwise.stacktrek.mysql
  vars:
    mysql_datadir: "{{disk.mount}}/{{disk.data_folder}}"
