---
- debug: var=dns_record_list
  tags: debug

- import_role:
    name: aws_utils
    tasks_from: collect_instance_info_speedy
    
- include_tasks: tagstovars.yml

- import_role: 
    name: aws_utils
    tasks_from: datadisk
  when: disk is defined

- name: aws tasks complete
  debug: 
    msg: aws postactions
  changed_when: yes
  notify: "aws postactions"
  tags: debug
